# permissions for end users to edit redis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: redis-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubecon-us-2019
    app.kubernetes.io/part-of: kubecon-us-2019
    app.kubernetes.io/managed-by: kustomize
  name: redis-editor-role
rules:
- apiGroups:
  - webapp.arpan.dev
  resources:
  - redis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.arpan.dev
  resources:
  - redis/status
  verbs:
  - get
